[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = ["__pycache__"]

[tool.ruff.lint]
select = [
  "E",
  "F",
  "I",
  "B",
  "UP",
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["backend"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
